/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2024-11-17 17:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import servidor.DataCliente;
import servidor.DataAerolinea;

public final class side_002dmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("servidor.DataCliente");
    _jspx_imports_classes.add("servidor.DataAerolinea");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Menu Lateral</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/side-menu.css\">\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"main-side-menu\" class=\"side-menu\">\n");
      out.write("        <ul class=\"list-unstyled ps-0\">\n");
      out.write("            <div id=\"perfil-submenu-div\" class=\"div-submenu\">\n");
      out.write("                <li class=\"mb-1\">\n");
      out.write("                ");

				    Object usuario = session.getAttribute("usuario");
				    String nickname = "";
				    if (usuario instanceof DataCliente) {
				        nickname = ((DataCliente) usuario).getNickname();  
				    } else if (session.getAttribute("tipoUsuario") != null && "aerolinea".equals(session.getAttribute("tipoUsuario"))) {
				        nickname = (String) usuario;
				    }
				
      out.write("\n");
      out.write("                            ");
 
                    String tipoUsuario = (String) session.getAttribute("tipoUsuario");
                    if ("cliente".equals(tipoUsuario)) { 
                
      out.write("\n");
      out.write("                            <p class=\"subtitle\"><a href=\"profile?nickname=");
      out.print( nickname );
      out.write("\" target=\"_PARENT\">Mi perfil</a></p>                    <div id=\"perfil-submenu\" class=\"submenu\">\n");
      out.write("                            <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("                                <li><a href=\"./reserva-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Reservar Vuelo</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-reserva\" class=\"link-dark rounded\" target=\"_PARENT\">Mis Reservas</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-usuario\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Usuarios</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-ruta-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Rutas de Vuelo</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-vuelos\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Vuelos</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-check-in\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar CheckIn</a></li>\n");
      out.write("                            ");
 } else if ("aerolinea".equals(tipoUsuario)) { 
      out.write("\n");
      out.write("                            <p class=\"subtitle\"><a href=\"profile_aerolinea?nickname=");
      out.print( nickname );
      out.write("\" target=\"_PARENT\">Mi perfil</a></p>                    <div id=\"perfil-submenu\" class=\"submenu\">\n");
      out.write("                            <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("                                <li><a href=\"./alta-ruta-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Nueva Ruta</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-ruta-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Rutas de Vuelo</a></li>\n");
      out.write("			                    <li><a href=\"./alta-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Nuevo Vuelo</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-vuelos\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Vuelos</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-usuario\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Usuarios</a></li>\n");
      out.write("			                    <li><a href=\"./consulta-reserva\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Reservas</a></li>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                            <p class=\"subtitle\">Acciones</p>                    <div id=\"perfil-submenu\" class=\"submenu\">\n");
      out.write("                            <ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("                                <li><a href=\"./consulta-usuario\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Usuarios</a></li>\n");
      out.write("                                <li><a href=\"./consulta-ruta-vuelo\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Rutas de Vuelo</a></li>\n");
      out.write("                                <li><a href=\"./consulta-vuelos\" class=\"link-dark rounded\" target=\"_PARENT\">Consultar Vuelos</a></li>\n");
      out.write("                        	");
 } 
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("            </div>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
