
package servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorVuelos", targetNamespace = "http://servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    servidor.ObjectFactory.class
})
public interface PublicadorVuelos {


    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataVuelo
     * @throws VueloNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorVuelos/verInfoVueloRequest", output = "http://servidor/PublicadorVuelos/verInfoVueloResponse", fault = {
        @FaultAction(className = VueloNoExisteExce_Exception.class, value = "http://servidor/PublicadorVuelos/verInfoVuelo/Fault/VueloNoExisteExce")
    })
    public DataVuelo verInfoVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws VueloNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorVuelos/confirmarAltaVueloRequest", output = "http://servidor/PublicadorVuelos/confirmarAltaVueloResponse")
    public boolean confirmarAltaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws ClientePasajeroRepetidoExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorVuelos/reservarVueloRequest", output = "http://servidor/PublicadorVuelos/reservarVueloResponse", fault = {
        @FaultAction(className = ClientePasajeroRepetidoExce_Exception.class, value = "http://servidor/PublicadorVuelos/reservarVuelo/Fault/ClientePasajeroRepetidoExce")
    })
    public void reservarVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        TipoAsiento arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        StringArray arg6)
        throws ClientePasajeroRepetidoExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataRutaVueloArray
     * @throws UsuarioNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorVuelos/listarRutasVuelosPorAerolineaRequest", output = "http://servidor/PublicadorVuelos/listarRutasVuelosPorAerolineaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteExce_Exception.class, value = "http://servidor/PublicadorVuelos/listarRutasVuelosPorAerolinea/Fault/UsuarioNoExisteExce")
    })
    public DataRutaVueloArray listarRutasVuelosPorAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataVueloArray
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorVuelos/listarVuelosPorRutaVueloRequest", output = "http://servidor/PublicadorVuelos/listarVuelosPorRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorVuelos/listarVuelosPorRutaVuelo/Fault/RVNoExisteExce")
    })
    public DataVueloArray listarVuelosPorRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataReservaArray
     * @throws VueloNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorVuelos/listarReservasDeVueloRequest", output = "http://servidor/PublicadorVuelos/listarReservasDeVueloResponse", fault = {
        @FaultAction(className = VueloNoExisteExce_Exception.class, value = "http://servidor/PublicadorVuelos/listarReservasDeVuelo/Fault/VueloNoExisteExce")
    })
    public DataReservaArray listarReservasDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws VueloNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws NombreVRepetidoExce_Exception
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorVuelos/ingresarDatosVueloRequest", output = "http://servidor/PublicadorVuelos/ingresarDatosVueloResponse", fault = {
        @FaultAction(className = NombreVRepetidoExce_Exception.class, value = "http://servidor/PublicadorVuelos/ingresarDatosVuelo/Fault/NombreVRepetidoExce"),
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorVuelos/ingresarDatosVuelo/Fault/RVNoExisteExce")
    })
    public void ingresarDatosVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws NombreVRepetidoExce_Exception, RVNoExisteExce_Exception
    ;

}
