
package servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorRutasVuelo", targetNamespace = "http://servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    servidor.ObjectFactory.class
})
public interface PublicadorRutasVuelo {


    /**
     * 
     * @return
     *     returns servidor.DataRutaVueloArray
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/listarRutasVueloRequest", output = "http://servidor/PublicadorRutasVuelo/listarRutasVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/listarRutasVuelo/Fault/RVNoExisteExce")
    })
    public DataRutaVueloArray listarRutasVuelo()
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws AerolineaNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/seleccionarAerolineaRequest", output = "http://servidor/PublicadorRutasVuelo/seleccionarAerolineaResponse", fault = {
        @FaultAction(className = AerolineaNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/seleccionarAerolinea/Fault/AerolineaNoExisteExce")
    })
    public void seleccionarAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws AerolineaNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/seleccionarRutaVueloRequest", output = "http://servidor/PublicadorRutasVuelo/seleccionarRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/seleccionarRutaVuelo/Fault/RVNoExisteExce")
    })
    public void seleccionarRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws CategoriaRepetidaExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/ingresarCategoriaRequest", output = "http://servidor/PublicadorRutasVuelo/ingresarCategoriaResponse", fault = {
        @FaultAction(className = CategoriaRepetidaExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/ingresarCategoria/Fault/CategoriaRepetidaExce")
    })
    public void ingresarCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws CategoriaRepetidaExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataCategoria
     * @throws CategoriaNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/getCategoriaRequest", output = "http://servidor/PublicadorRutasVuelo/getCategoriaResponse", fault = {
        @FaultAction(className = CategoriaNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/getCategoria/Fault/CategoriaNoExisteExce")
    })
    public DataCategoria getCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws CategoriaNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataRutaVueloArray
     * @throws UsuarioNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/listarRutasVueloPorAerolineaRequest", output = "http://servidor/PublicadorRutasVuelo/listarRutasVueloPorAerolineaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/listarRutasVueloPorAerolinea/Fault/UsuarioNoExisteExce")
    })
    public DataRutaVueloArray listarRutasVueloPorAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/modificarDatosRutaVueloRequest", output = "http://servidor/PublicadorRutasVuelo/modificarDatosRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/modificarDatosRutaVuelo/Fault/RVNoExisteExce")
    })
    public void modificarDatosRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        float arg7,
        @WebParam(name = "arg8", partName = "arg8")
        float arg8,
        @WebParam(name = "arg9", partName = "arg9")
        ArrayList arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/finalizarRutaVueloRequest", output = "http://servidor/PublicadorRutasVuelo/finalizarRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/finalizarRutaVuelo/Fault/RVNoExisteExce")
    })
    public void finalizarRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/agregarVisitaRutaVueloRequest", output = "http://servidor/PublicadorRutasVuelo/agregarVisitaRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/agregarVisitaRutaVuelo/Fault/RVNoExisteExce")
    })
    public void agregarVisitaRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @return
     *     returns servidor.CategoriaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/listarCategoriasRequest", output = "http://servidor/PublicadorRutasVuelo/listarCategoriasResponse")
    public CategoriaArray listarCategorias();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg12
     * @param arg13
     * @param arg14
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws NombreRVRepetidoExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/registrarRutaDeVueloRequest", output = "http://servidor/PublicadorRutasVuelo/registrarRutaDeVueloResponse", fault = {
        @FaultAction(className = NombreRVRepetidoExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/registrarRutaDeVuelo/Fault/NombreRVRepetidoExce")
    })
    public void registrarRutaDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        float arg7,
        @WebParam(name = "arg8", partName = "arg8")
        float arg8,
        @WebParam(name = "arg9", partName = "arg9")
        StringArray arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        String arg12,
        @WebParam(name = "arg13", partName = "arg13")
        String arg13,
        @WebParam(name = "arg14", partName = "arg14")
        String arg14)
        throws NombreRVRepetidoExce_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/listarCiudadesDisponiblesRequest", output = "http://servidor/PublicadorRutasVuelo/listarCiudadesDisponiblesResponse")
    public StringArray listarCiudadesDisponibles();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws NicknameRepetidoExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorRutasVuelo/registrarCiudadRequest", output = "http://servidor/PublicadorRutasVuelo/registrarCiudadResponse", fault = {
        @FaultAction(className = NicknameRepetidoExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/registrarCiudad/Fault/NicknameRepetidoExce")
    })
    public void registrarCiudad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws NicknameRepetidoExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.ArrayList
     * @throws UsuarioNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/listarRutasVueloIngresadasPorAerolineaRequest", output = "http://servidor/PublicadorRutasVuelo/listarRutasVueloIngresadasPorAerolineaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/listarRutasVueloIngresadasPorAerolinea/Fault/UsuarioNoExisteExce")
    })
    public ArrayList listarRutasVueloIngresadasPorAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataRutaVuelo
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorRutasVuelo/verInfoRutaVueloRequest", output = "http://servidor/PublicadorRutasVuelo/verInfoRutaVueloResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorRutasVuelo/verInfoRutaVuelo/Fault/RVNoExisteExce")
    })
    public DataRutaVuelo verInfoRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws RVNoExisteExce_Exception
    ;

}
