
package servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorPaquete", targetNamespace = "http://servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorPaquete {


    /**
     * 
     * @return
     *     returns servidor.DataPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorPaquete/listarPaquetesDisponiblesRequest", output = "http://servidor/PublicadorPaquete/listarPaquetesDisponiblesResponse")
    public DataPaqueteArray listarPaquetesDisponibles();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DataPaquete
     * @throws VueloNoExisteExce_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/PublicadorPaquete/verInfoPaqueteRequest", output = "http://servidor/PublicadorPaquete/verInfoPaqueteResponse", fault = {
        @FaultAction(className = VueloNoExisteExce_Exception.class, value = "http://servidor/PublicadorPaquete/verInfoPaquete/Fault/VueloNoExisteExce")
    })
    public DataPaquete verInfoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws VueloNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws RVNoExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorPaquete/agregarRVaPaqueteRequest", output = "http://servidor/PublicadorPaquete/agregarRVaPaqueteResponse", fault = {
        @FaultAction(className = RVNoExisteExce_Exception.class, value = "http://servidor/PublicadorPaquete/agregarRVaPaquete/Fault/RVNoExisteExce")
    })
    public void agregarRVaPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        TipoAsiento arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3)
        throws RVNoExisteExce_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws PaqueteExisteExce_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/PublicadorPaquete/comprarPaqueteRequest", output = "http://servidor/PublicadorPaquete/comprarPaqueteResponse", fault = {
        @FaultAction(className = PaqueteExisteExce_Exception.class, value = "http://servidor/PublicadorPaquete/comprarPaquete/Fault/PaqueteExisteExce")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        LocalDate arg2,
        @WebParam(name = "arg3", partName = "arg3")
        LocalDate arg3)
        throws PaqueteExisteExce_Exception
    ;

}
