
package servidor;

import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorVuelosService", targetNamespace = "http://servidor/")
public class PublicadorVuelosService extends Service {

	private final static QName PUBLICADORVUELOSSERVICE_QNAME = new QName("http://servidor/", "PublicadorVuelosService");

    public PublicadorVuelosService() throws MalformedURLException {
        super(getDynamicWsdlUrl(), PUBLICADORVUELOSSERVICE_QNAME);
    }

    public PublicadorVuelosService(WebServiceFeature... features) throws MalformedURLException {
        super(getDynamicWsdlUrl(), PUBLICADORVUELOSSERVICE_QNAME, features);
    }

    private static URL getDynamicWsdlUrl() {
        Properties properties = new Properties();
        try {
            String configPath = System.getProperty("user.home") + "/.volandoUy/config.properties";
            properties.load(new FileInputStream(configPath));

            String hostIP = properties.getProperty("hostIP", "localhost");
            String hostPort = properties.getProperty("hostPortVuelos", "9102");
            String wsdlPath = "/PublicadorVuelos?wsdl";

            String wsdlUrl = "http://" + hostIP + ":" + hostPort + wsdlPath;
            return new URL(wsdlUrl);
        } catch (IOException e) {
            throw new RuntimeException("Error al cargar la URL del WSDL desde config.properties", e);
        }
    }

    public PublicadorVuelos getPublicadorVuelosPort() {
        return super.getPort(new QName("http://servidor/", "PublicadorVuelosPort"), PublicadorVuelos.class);
    }

    public PublicadorVuelos getPublicadorVuelosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "PublicadorVuelosPort"), PublicadorVuelos.class, features);
    }
}