
package servidor;

import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorRutasVueloService", targetNamespace = "http://servidor/")
public class PublicadorRutasVueloService extends Service {

	private final static QName PUBLICADORRUTASVUELOSERVICE_QNAME = new QName("http://servidor/", "PublicadorRutasVueloService");

    public PublicadorRutasVueloService() throws MalformedURLException {
        super(getDynamicWsdlUrl(), PUBLICADORRUTASVUELOSERVICE_QNAME);
    }

    public PublicadorRutasVueloService(WebServiceFeature... features) throws MalformedURLException {
        super(getDynamicWsdlUrl(), PUBLICADORRUTASVUELOSERVICE_QNAME, features);
    }

    private static URL getDynamicWsdlUrl() {
        Properties properties = new Properties();
        try {
            String configPath = System.getProperty("user.home") + "/.volandoUy/config.properties";
            properties.load(new FileInputStream(configPath));

            String hostIP = properties.getProperty("hostIP", "localhost");
            String hostPort = properties.getProperty("hostPortRutasVuelo", "9101");
            String wsdlPath = "/PublicadorRutasVuelo?wsdl";

            String wsdlUrl = "http://" + hostIP + ":" + hostPort + wsdlPath;
            return new URL(wsdlUrl);
        } catch (IOException e) {
            throw new RuntimeException("Error al cargar la URL del WSDL desde config.properties", e);
        }
    }

    public PublicadorRutasVuelo getPublicadorRutasVueloPort() {
        return super.getPort(new QName("http://servidor/", "PublicadorRutasVueloPort"), PublicadorRutasVuelo.class);
    }

    public PublicadorRutasVuelo getPublicadorRutasVueloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "PublicadorRutasVueloPort"), PublicadorRutasVuelo.class, features);
    }
}